spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thongkao_dev?characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: user
    password: password
    maximumPoolSize: 300